### ISSUE TITLE
Does not work on latest OS X Mountain Lion

### ISSUE THREAD

**Issue by dalvarez** [liquidx/webviewscreensaver#1]
Correct me if I'm wrong (I hope I am, this looks too cool not to use), but I cannot install this screensaver on my computer because it considers this an app made from "an unidentified developer." I think this is from recent changes to how installations can only come through the Mac App Store. Anyway this could be put up there so that more of us can use it?

**Comment by liquidx** [comment]
I've just updated the latest release to 2.0 with it now signed with my Developer ID:

https://github.com/liquidx/webviewscreensaver/releases
