### ISSUE TITLE
Put version 1.2 up as a download!

### ISSUE THREAD

**Issue by JamesHagerman** [liquidx/webviewscreensaver#10]
Hey,

I noticed that 1.0 is still on GitHub for download but the code builds version 1.2.

You should update the downloads section so that 1.2 is available. Also, put it under the releases section!

Thanks!

**Comment by jcushman** [comment]
Ditto, this would be helpful. Thanks!

**Comment by liquidx** [comment]
Put up 2.0 up and in the release section.

https://github.com/liquidx/webviewscreensaver/releases
