### ISSUE TITLE
Screensaver crashes out to desktop (or login screen)

### ISSUE THREAD

**Issue by TheKosmonaut** [liquidx/webviewscreensaver#11]
Added the following site into the url dialog box:  http://www.ustream.tv/channel/iss-hdev-payload/pop-out
 and while it works for a few seconds, it will inevitably cut out and pop back into the desktop or the login screen. I checked console and this is the error I see when that comes up 

May 18 00:33:29 Anthonys-MacBook-Air.local loginwindow[93]: ERROR | -[LWBuiltInScreenLockAuthLion closeAuthAndReset:] | Attempted to remove an observer when not observing        

I tried changing the timing of it all re; the screensaver start time and password requirements, no luck. 

Info: Macbook Air 2010, OS X 10,10,4

**Comment by liquidx** [comment]
I just updated the source and the release to 2.0 with support for 10.10. Can you check that release out to see if this works for you?

https://github.com/liquidx/webviewscreensaver/releases
