### ISSUE TITLE
Viewing live IP web camera, preview works, but actual screensaver it does not

### ISSUE THREAD

**Issue by supak111** [liquidx/webviewscreensaver#13]
Latest Yosemite, MacBook Pro Retina.

I was able to get this to work to view a live stream from my foscom ip camera. Works great when you try to use it in system preferences and you click "Preview" BUT does not play the live webcam video when you test it in the actually screen saver. The box where the ip camera video goes is just black/blank

**Comment by agologan** [comment]
Please retest this with our new version `v2.1`.

**Comment by supak111** [comment]
New version seems to work.
