### ISSUE TITLE
Can not view self signed SSL cert sites.

### ISSUE THREAD

**Issue by skwashua** [liquidx/webviewscreensaver#15]
Unable to view sites with a self signed SSL cert.  This would be helpful in enterprise environments.  (Viewing Xcode Bots in my case)

**Comment by ratkins** [comment]
I have found a workaround: hit the bots bigscreen URL in Chrome (https://my-ci-machine.local/xcode/bigscreen), click the red padlock in the browser URL bar, then click "Certificate Information", then drag the certificate icon onto your desktop. Double click it and add it to your System keychain.

Find the certificate in Keychain Access, double click it, then expand the "Trust" disclosure indicator. Select "Always Trust". 

You should now be able to see your Bots Bigscreen display as a screensaver.

**Comment by ratkins** [comment]
Follow-up: Trying this again, the latest version of Chrome (Version 51.0.2704.103 (64-bit)) seems to have lost the ability to trust a certificate, and the version of Safari I'm using (Version 9.1.1 (11601.6.17)) seems to have gained it.

After deleting a previous version of the certificate from Keychain (the machine moved networks), hitting the Big Screen URL in Safari came up with a dialog with a checkbox asking me if I wanted to trust the self-signed cert. When I did, the preview in the Screen Savers preferences panel worked.

**Comment by liquidx** [comment]
I believe if the self-signed certificate is added to the Keychain, then Safari (and the WebView) will be able to trust it. 

Closing this issue for now since there seems to be a workaround.
