### ISSUE TITLE
Framerate in this app vs Safari

### ISSUE THREAD

**Issue by philipbulley** [liquidx/webviewscreensaver#16]
Anyone know why https://www.tumblr.com/tv has a good framerate in Safari, but suffers significantly when loaded into this screensaver?

**Comment by klimenko** [comment]
I have same problem with YouTube. 
'hd=1' has no effect in 'https://www.youtube.com/embed/UGPuEDyAsU8?hd=1&amp;autoplay=1', but this works fine in Safari.

**Comment by ROUND** [comment]
I can confirm that any movement or animation in this wrapper has a significantly lower frame rate than in the browser.

**Comment by liquidx** [comment]
I'm not sure why it might have a lower frame rate than Safari. I suspect the WebView that's used in Safari is different from the one that is exposed for developers.

I generally get pretty good framerates on my 2014 MacBook Air for youtube videos though.

**Comment by liquidx** [comment]
This may not be something we can do anything about. Closing this issue for now.

**Comment by round** [comment]
Just used this solution on another project that solved all issues with 2D canvas performance in WebViews like this: https://stackoverflow.com/a/36363908

**Comment by EmersonYe** [comment]
@round I tried the workaround of enabling accelerated canvas rendering to no avail.

I ran
```
defaults write net.liquidx.WebViewScreenSaver WebKitAccelerated2dCanvasEnabled -bool true
defaults write net.liquidx.WebViewScreenSaver WebKitAcceleratedDrawingEnabled -bool true
defaults write net.liquidx.WebViewScreenSaver WebKitCanvasUsesAcceleratedDrawing -bool true
```
in terminal, then built the application and installed it. The website still rendered extremely slowly (<10 fps).

[The website](https://storage.googleapis.com/static_webpage/index.html) I am setting as my background uses `requestAnimationFrame()` to draw on the canvas. I wonder why the suggested websites in the README render fine and mine doesn't.

**Comment by denishowe** [comment]
I can't see the app set [animationTimeInterval](https://developer.apple.com/documentation/screensaver/screensaverview/1512484-animationtimeinterval) anywhere.

I read somewhere that the default is one second, which would explain why, e.g. http://foldoc.org/pub/js/clock.html (JavaScript canvas animation) runs smoothly in Safari but jerkily in webviewscreensaver.

Would setting this to a really low value (a) solve the problem and (b) be a good idea?
