### ISSUE TITLE
Include http headers for the url request

### ISSUE THREAD

**Issue by egaga** [liquidx/webviewscreensaver#18]
Would it be possible to include http headers to the url request.

Use case: There are some protected websites that cannot be shown because they require the basic authentication header. With this feature, the basic authentication header could be set, and thus enable accessing a password-protected site.

**Comment by liperuf** [comment]
Possibly connected with issue #31

**Comment by agologan** [comment]
`v2.3+` adds support for previewing and interacting with websites during configuration.
Cookies and storage is shared in the context of the screensaver.

It's not exactly as requested, but should allow authentication.

If you wanted to fork and provide your own configuration you could call `- loadRequest:` on the webView and pass in a request with `- setValue:forHTTPHeaderField:`.
We aim to keep the project simple and can't see an UX that fits at this time.
