### ISSUE TITLE
Will not open under 10.6.8

### ISSUE THREAD

**Issue by DobyTang** [liquidx/webviewscreensaver#2]
Download the link, into downloads folder

Have the WebiewScreenSaver.saver file

double click, and get the following

![screen shot 2013-07-12 at 15 51 07](https://f.cloud.github.com/assets/1828678/788717/8d076232-eb02-11e2-8213-de7934bd3ec3.jpg)

which implies its corrupt

Anyone any ideas?

**Comment by liquidx** [comment]
I'm afraid the code doesn't support 10.6.
