### ISSUE TITLE
Add ability to hardcode a default URL into the distribution

### ISSUE THREAD

**Issue by BHSPitMonkey** [liquidx/webviewscreensaver#21]
Hi, thanks for making this!

I'd like to give a webviewscreensaver build zip out to a few less-technically-inclined people, and it would be cool if I could just modify a key in the Info.plist (or elsewhere in the package) before giving it to them to save them the effort of copy/pasting the URL themselves.

Is it possible that webviewscreensaver could try to read this value when no existing user configuration exists?

**Comment by jononon** [comment]
^ This would be incredibly helpful

**Comment by BHSPitMonkey** [comment]
I'll work on a PR for this.

**Comment by liquidx** [comment]
That's a great idea - I'll take a look at the PR soon. Thanks!
