### ISSUE TITLE
feature request: user defined amount of monitors in use

### ISSUE THREAD

**Issue by esaruoho** [liquidx/webviewscreensaver#28]
Hi, I just tried this and it booted up two safari webviews playing a YouTube channel playlist - so th music, was, of course, playing twice, since I have two monitors. Could it be possible to offer a setting where one can decide whether the screensaver will run on one screen or two?

**Comment by agologan** [comment]
In the mean time just copy the YouTube embed link and add `mute=1` to it because why would you want a screensaver with sound?
E.g. https://www.youtube.com/embed/XBPjVzSoepo?rel=0&autoplay=1;mute=1;controls=0

**Comment by agologan** [comment]
Closing this as a duplicate of #12
