### ISSUE TITLE
Options panel has become locked.

### ISSUE THREAD

**Issue by mhoydis** [liquidx/webviewscreensaver#3]
OS X Mavericks.  The options panel of the WebViewScreensaver has become locked somehow.  It was working fine, then I rebooted for an unrelated reason.  Now, I'm unable to modify the value of either the URL or Minutes fields.  Clicking either the Add or Remove URL button had no effect, but produces the following error in Console...

1/23/14 3:40:36.463 PM System Preferences[406]: -[__NSCFArray insertObject:atIndex:]: mutating method sent to immutable object
1/23/14 3:40:36.465 PM System Preferences[406]: (
	0   CoreFoundation                      0x00007fff8c45a41c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8ce9fe75 objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8c45a2cc +[NSException raise:format:] + 204
	3   CoreFoundation                      0x00007fff8c452462 -[__NSCFArray insertObject:atIndex:] + 98
	4   WebViewScreenSaver                  0x00000001082d470e -[WebViewScreenSaverView addRow:] + 124
	5   AppKit                              0x00007fff945203d0 -[NSApplication sendAction:to:from:] + 327
	6   AppKit                              0x00007fff9452024e -[NSControl sendAction:to:] + 86
	7   AppKit                              0x00007fff9456cd7d -[NSCell _sendActionFrom:] + 128
	8   AppKit                              0x00007fff94586715 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 2316
	9   AppKit                              0x00007fff94585ae7 -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 487
	10  AppKit                              0x00007fff945851fd -[NSControl mouseDown:] + 706
	11  AppKit                              0x00007fff94506d08 -[NSWindow sendEvent:] + 11296
	12  AppKit                              0x00007fff944a5744 -[NSApplication sendEvent:] + 2021
	13  System Preferences                  0x0000000100552eb4 System Preferences + 28340
	14  AppKit                              0x00007fff942f5a29 -[NSApplication run] + 646
	15  AppKit                              0x00007fff942e0803 NSApplicationMain + 940
	16  libdyld.dylib                       0x00007fff8c0e65fd start + 1
)

I have tried to Repair Permissions feature of the Disk Utility tool, didn't fix it.

Any ideas?
-Michael

**Comment by htmldoug** [comment]
Same here on 10.9.5.

I was able to reset things with `rm ~/Library/Preferences/ByHost/WebViewScreenSaver*` and a reboot. Then it happened again.

**Comment by liquidx** [comment]
I believe I've fixed some of these odd issues in the newest 2.0 release.

https://github.com/liquidx/webviewscreensaver/releases
