### ISSUE TITLE
Cookies/login don't work

### ISSUE THREAD

**Issue by benbuckman** [liquidx/webviewscreensaver#31]
Thanks for creating this!

The readme says,

> The web page runs as though you opened it in Safari

I'm trying to view a page that requires login. I'm logged in in Safari, with "remember me" and Safari remembering the password.
When I run the screen saver, however, I get the page's logged-out state.

Suggestions?
Thanks

**Comment by beatrichartz** [comment]
👍 seeing the same issue

**Comment by AYapejian** [comment]
Same here as well... too bad, this is simple and useful if cookies / local storage worked correctly ( or allow keyboard interactions so we can set the session manually )

**Comment by loadedsith** [comment]
Does anyone know if webviews can store cookies in this way? I'm getting the impression they can't.

**Comment by agologan** [comment]
`v2.3` provides preview and user interaction.
Cookies are shared just in the context of the screensaver.
