### ISSUE TITLE
Screensaver loads and then crashes out

### ISSUE THREAD

**Issue by gregumm** [liquidx/webviewscreensaver#34]
Screensaver starts and crashes back to desktop about 10 seconds later. Similar to a previously closed issue, it's when using the ISS live video feed. Here's the error message in console. 

Windows Server (CoreDisplay)

[ERROR] - Driver reported mode info is out of sync with current mode info. Display 4280b80, driver's bytePerRow = 11776, driver's width = 3360, stored width = 3360. Forcing rowbytes to be 4*modeInfo->ioModeInfo.nominalwitdh.

**Comment by liquidx** [comment]
What OS and hardware is this happening on?

**Comment by gregumm** [comment]
Sierra v10.12.2
MBP 15-inch, Mid 2015

![image](https://cloud.githubusercontent.com/assets/24858310/21594058/39c246f6-d0db-11e6-851e-adf5ed0d93f5.png)

**Comment by phillyDesignr** [comment]
I just upgraded to Sierra 10.12 and :
<img width="498" alt="screenshot 2017-01-30 17 12 41" src="https://cloud.githubusercontent.com/assets/266512/22444136/b59cf72c-e70f-11e6-8f7a-f9648b1286b8.png">

Hardware:
<img width="566" alt="screenshot 2017-01-30 17 16 10" src="https://cloud.githubusercontent.com/assets/266512/22444157/cde68230-e70f-11e6-9644-4ee2e702188a.png">

**Comment by JasPanesar** [comment]
Hi, wondering if the Sierra incompatibilities have been addressed?  Would like to give this a go.

**Comment by liquidx** [comment]
This is the only report of a crash in Sierra. I am using it on Sierra
without issue. Can you see if you can get the crash report and attach it
after you press the "Show Details" button?

**Comment by agologan** [comment]
Outdated bug report with crash information.
Please use our newer version `v2.1` compatible with **Catalina** and get back to us if any more issues occur.
