### ISSUE TITLE
Add WebView to Screen Saver settings so you can authenticate.

### ISSUE THREAD

**Issue by liquidx** [liquidx/webviewscreensaver#35]
One way to allow the screensaver to use authenticated sites as a dashboard is to add mini-browser in the settings so that people can sign in to a site and have the cookies persist in the cookie jar.

It shouldn't be too hard to implement.

**Comment by joshboyden** [comment]
@liquidx I would love this feature! I'm trying to display a Jenkins dashboard using the [Jenkins Build Monitor Plugin ](https://github.com/jan-molak/jenkins-build-monitor-plugin), but the display formatting for the dashboard is saved in cookies.

**Comment by PekopT** [comment]
+1

**Comment by cvand** [comment]
+1

**Comment by asleepwalker** [comment]
+1.

**Comment by ryankeefer** [comment]
+1

**Comment by bojanstef** [comment]
@joshboyden any updates on this?

**Comment by Rayrn** [comment]
+1

**Comment by liyaodong** [comment]
+1

**Comment by jammydav93** [comment]
+1, is there any update on this?

**Comment by absimpson** [comment]
+1

**Comment by robertgranholm** [comment]
update?

**Comment by mcgrealife** [comment]
Any workarounds to this yet?

**Comment by leavez** [comment]
Check out my fork, which implements this feature https://github.com/leavez/webviewscreensaver/releases/tag/v2.3

**Comment by rickoneeleven** [comment]
> Check out my fork, which implements this feature https://github.com/leavez/webviewscreensaver/releases/tag/v2.3

how do we install this one though? thanks ❤

**Comment by agologan** [comment]
Official v2.3 now available which should provide a similar experience to the fork created by @leavez .
Thanks buddy for taking a stab at it way before we had any time to.
