### ISSUE TITLE
How to uninstall for all users

### ISSUE THREAD

**Issue by moheinz** [liquidx/webviewscreensaver#36]
I have a new MAC Mini.  I installed this application and it was working well for a few weeks.  Now, I cannot login as a local Admin because it goes straight the webscreensaver which I cannot get out of.  I have the MAC on our network and can login as a network user without the screen saver coming up.  I created a new local Admin account and the same thing is happening where the screen saver comes up immediately and I cannot get out of it.  I need to remove all traces of this application for all users.  How can I do that so I can use this MAC again?  It is critical I get this resolved quickly.
Thanks for your help.

**Comment by agologan** [comment]
_This didn't get resolved quickly._

For posterity if anybody has found this issue.
Screensavers installed for all users are found in `/Library/Screen\ Saver` while those installed for the current user are in `~/Library/Screen\ Saver`.

To remove it just:
``` bash
sudo rm -rf /Library/Screen\ Savers/WebViewScreenSaver.saver
```
