### ISSUE TITLE
Tip/Enhancement, the  Full Screen Youtube playlists.

### ISSUE THREAD

**Issue by MichaelDimmitt** [liquidx/webviewscreensaver#38]
@liquidx, This may have already been implemented by others.

But I did not see the implementation anywhere else so I thought that I would share. 😂 
Using videos that follow this convention webview screensaver can go through youtube playlist of any size.

Try it for yourself: https://www.youtube.com/embed/durCuF6jb8k?rel=0&autoplay=1&list=PLZbIo_dYB77vgAus0es8Ul3kFkRYIRjJc&index=1&?rel=0&autoplay=1

cheers, MichaelDimmitt

**Comment by agologan** [comment]
Thank you for your suggestion.
