### ISSUE TITLE
Use the  WKWebView  class instead of using WebView

### ISSUE THREAD

**Issue by EstherSalinas** [liquidx/webviewscreensaver#41]
Hi,

Congratulations for your project.
I'm using OS X 10.11 and this screen saver works for the README examples. But I have a web that uses arrow functions (I'm not sure if it is the reason) the screensaver is shown in black colour.
I've read this in apple page:

In apps that run in OS X 10.10 and later, use the 
WKWebView
 class instead of using WebView.

https://developer.apple.com/documentation/webkit/wkwebview

Thank you in advance,

Esther.

**Comment by pavellishin** [comment]
> (I'm not sure if it is the reason)

An accessible Javascript console of some sort would be helpful, too :/

**Comment by jtoy** [comment]
+1 . It runs too slow on WebView, the speed  of executing pages is supposedly much faster on WKWebView

**Comment by pavellishin** [comment]
>  It runs too slow on WebView

I've noticed it's not super speedy, myself.

I've never opened up XCode in my life, except to update it. Is this something that's difficult to change, or is it literally just changing an import? @liquidx mentioned that he's doing maintenance, but not active development; I could try it, but I don't really want to sink three days into something that would take an experienced dev two hours.

**Comment by jtoy** [comment]
I have not done XCode either, but I was able to load the project in XCode and compile it. I think updating it to use WKWebView should be fairly easy: https://stackoverflow.com/questions/32290198/osx-webview-very-slow-and-laggy

**Comment by round** [comment]
This may be a helpful workaround: https://github.com/liquidx/webviewscreensaver/issues/16#issuecomment-351837159.

**Comment by agologan** [comment]
We switched to WKWebView in the latest version `v2.1`.
