### ISSUE TITLE
Set fontSize and numberOfColumns via querystring

### ISSUE THREAD

**Issue by is-digital-services** [liquidx/webviewscreensaver#43]
Would it be possible to set the fontSize and numberOfColumns via querystring parameters?  I am using a screensaver that does not have navigatable feature to allow me to set those preferences directly.  However it does take a URL and it would be great to be able to add these settings in the URL.

**Comment by agologan** [comment]
I assume you're asking if you can modify the display of a specific website via URI query parameters.
If that feature is not implemented by the website then the answer is **NO**.

You could create a bookmarklet that modifies the target website, or embed your website in an iframe modify it via javascript and load that instead.
