### ISSUE TITLE
javascript pages are extremely slow

### ISSUE THREAD

**Issue by jtoy** [liquidx/webviewscreensaver#46]
tested with this page ( i wrote it): https://www.pushpopchallenge.com/submissions/nAB28A

any way to speed this up. it runs fine everywhere else including an iphone 5s.

**Comment by EmersonYe** [comment]
I'm experiencing the same issues with [my website](https://storage.googleapis.com/static_webpage/index.html) as well.

I am using requestAnimationFrame, I wonder if it has anything to do with that.

**Comment by agologan** [comment]
We've switched to WKWebView in our latest version `v2.1`
Some content might still be sluggish in fullscreen compared to your browser window, but this should improve performance significantly.
