### ISSUE TITLE
macOS 10.13.3 

### ISSUE THREAD

**Issue by tolsadus** [liquidx/webviewscreensaver#47]
That app is incredible, and really cool. However, I've recently encounter the following error message.

You cannot use the WebViewScreenSaver screen saver with this version of macOS. Please contact the vendor to get a newer version of the screen saver.

Please see attached a screenshot https://imgur.com/a/NBYEH

Any ideas how could we perhaps fix this ?

**Comment by jaller94** [comment]
Version 2.0 works well for me on macOS 10.13.4.

**Comment by lipsumar** [comment]
Also fine on 10.14.4 (Mojave), but I had to close and re-open system preferences completely before it appeared in the list.
