### ISSUE TITLE
Press ESC to Cancel Screensaver?

### ISSUE THREAD

**Issue by coofercat** [liquidx/webviewscreensaver#48]
First up, I love this screensaver - it's a great way to quickly make a 'branded' screensaver on a work laptop, and with a bit of consideration make one way better than the usual corporate stuff

One thing I've noticed is that on returning to the computer, I have to make a mouse click to cancel the screensaver to get to the login prompt. Would it be possible to additionally allow pressing a key (in particular the ESC key) to do this?

My reasoning is that I can then completely control the computer using nothing but the keyboard, so no need to reach over to click the mouse, so my hands are ready in place to type in my password.

**Comment by sheykh-sleky** [comment]
I've noticed - on my iMini that doesn't have keyboard/mouse only video.  I cannot get the screensaver to stop even using a network KVM nor Screen Sharing.

**Comment by agologan** [comment]
No longer an issue please try our latest version `v2.1`.

**Comment by coofercat** [comment]
Awesome! Thank you very much - just given it a try, and it works perfectly :-)
