### ISSUE TITLE
Does not work for localhost

### ISSUE THREAD

**Issue by theblindprophet** [liquidx/webviewscreensaver#49]
I am trying to create my own HTML page and use that has a screensaver. I have served the page on localhost:8001 and set that as the url, but I do not get anything.

**Comment by EmersonYe** [comment]
To use your own HTML page, directly input your full path to your html file. No need to host it on localhost.

![image](https://user-images.githubusercontent.com/6600900/54066613-c29f9580-41e7-11e9-95a6-0815699e8a54.png)

**Comment by agologan** [comment]
No reason why localhost shouldn't work.
Test it in Safari first, if it loads up correctly.

Alternatively @EmersonYe is correct, just load the local path.
Please check our latest version and [README](https://github.com/liquidx/webviewscreensaver/blob/master/README.md) for more details on loading local content.
