### ISSUE TITLE
Can't change website

### ISSUE THREAD

**Issue by pbrewczynski** [liquidx/webviewscreensaver#5]
Hi. 

I tried to add local website as path. And it worked (you haven't said that this is possible).

But then I wanted to change it, and I can't do it. It looks like I've corrupted somehow your settings file...  Look at the vide : 

http://www.youtube.com/watch?v=Jfxhs_5diPA

Thanks for awesome screen saver ;)

**Comment by niccoX** [comment]
When I first installed it I could add/remove/edit sites. Now it just stopped. I didn't reboot, or log out.

Running OSX 10.10.

**Comment by DrTall** [comment]
I have the same problem.

**Comment by liquidx** [comment]
Hi all, I'm going to look in to this issue. I might have something to do with some changes in 10.10. I haven't released an update for many years so I suspect something incompatible just popped up.

**Comment by andyjagoe** [comment]
+1

**Comment by dbharding** [comment]
I have the same issue. Running 10.9 not 10.10. Also cannot find where the URL list is stored.

**Comment by liquidx** [comment]
This should now be fixed in the latest 2.0 release:

https://github.com/liquidx/webviewscreensaver/releases
