### ISSUE TITLE
Window Level - push it to desktop level

### ISSUE THREAD

**Issue by Miles-Tone** [liquidx/webviewscreensaver#50]
Hi there,

Really tasty stuff, Ive had a little play around in Xcode with this in High Sierra, and I'm trying to get this or similar in:
[self.window setLevel:kCGMinimumWindowLevel];

so that it can be used in conjunction with screensavertowallpaper - 
"/System/Library/CoreServices/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine -background > /dev/null 2>&1 &"

I can then have the ISS live feed as my desktop background :) 

With the structuring of the code, is this possible?

Thanks

**Comment by agologan** [comment]
This no longer works since **Mojave**, but if you still haven't upgraded and you want to give it a try our latest version should work, though we have no plans to support this feature since it has been removed from macOS/
