### ISSUE TITLE
Is there a way to use a website that requires user name and password

### ISSUE THREAD

**Issue by morbo3000** [liquidx/webviewscreensaver#51]
I am trying to use this a leaderboard from this website: 

https://teach.classdojo.com

Specifically, when I am logged in, this is the url I am trying to put into the screensaver. 

https://teach.classdojo.com/#/classes/5bc8c228fa5d2900184e1f7f/points

It requires a login so that my specific class shows up. 

Is there a way to do this? 

Thanks!

**Comment by robertgranholm** [comment]
I'd like this too

**Comment by rickvandermeij-aanzee** [comment]
this would be a security flaw of your website

**Comment by HackerKhush** [comment]
can you explain what is security flaw here?

> 
> 
> this would be a security flaw of your website

**Comment by rickoneeleven** [comment]
i'd like to too, just some interaction on the website so I can login at first, and then after that it can load the website as if it's logged in as me ❤

**Comment by barakharyati** [comment]
it will be great!

**Comment by agologan** [comment]
Try out `v2.3`. This allows preview and user interaction during configuration and cookies are shared in the context of the screensaver.
