### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by ddechamb** [liquidx/webviewscreensaver#52]
I absolutely love that app. But recently a new cookie warning appeared on http://www.ustream.tv/channel/live-iss-stream/pop-out

and no way to take it out! any idea? 

Thanks

**Comment by agologan** [comment]
Tested but I see no cookie warning present.
Unfortunately autoplay doesn't work on their player anymore as one idea would be to use their embed url:
https://ustream.tv/embed/9408562?html5ui=1&volume=0&autoplay=true

Alternatively there are people re-streaming them via YouTube:
https://www.youtube.com/embed/XBPjVzSoepo?rel=0&autoplay=1;mute=1;controls=0
https://www.youtube.com/embed/EEIk7gwjgIM?rel=0&autoplay=1;mute=1;controls=0
