### ISSUE TITLE
WebViewScreenSaver.saver is not a file, but a folder

### ISSUE THREAD

**Issue by codepiligrim** [liquidx/webviewscreensaver#55]
After unzipping archive WebViewScreenSaver-2.0.zip, content of extracted archive shows  WebViewScreenSaver.saver as a folder :D
![Capture](https://user-images.githubusercontent.com/23336138/66301635-2d40bd00-e900-11e9-88e3-721528064eee.PNG)

**Comment by liquidx** [comment]
Sorry, this doesn't work on Windows. It only works on a Mac.
