### ISSUE TITLE
AppStore

### ISSUE THREAD

**Issue by stevedekorte** [liquidx/webviewscreensaver#59]
Please consider posting this on the Apple App Store. I suspect many of us would be happy to purchase one that worked on current macs an avoided any install hassles.

**Comment by agologan** [comment]
Unfortunately app distribution via the App Store requires a yearly paid developer membership.
Our app is open-source and does not make any money to support that, so it's very unlikely it will ever be listed in the App Store.

That being said you can install our latest version using one line via [brew](https://brew.sh/)
```
brew cask install --no-quarantine webviewscreensaver
```
See our [README](https://github.com/liquidx/webviewscreensaver/blob/master/README.md) for more information.
