### ISSUE TITLE
Malware flag from MalwarePatrol engine (all others on VirusTotal report clean)

### ISSUE THREAD

**Issue by sanchezelton** [liquidx/webviewscreensaver#61]
I'm sure this is more likely an erroneous flag, but release 2.0 is raising a malicious flag with the MalwarePatrol engine (no other engines flag it as such). I have linked to the VirusTotal report: https://www.virustotal.com/gui/url/3a3278fa801be024822d82f71f55b856d78632f18031b9a9ea40ebc468b5e17c/detection

I'd like to use this to get an HTML version of the LCARS screensaver popular on Mac OS X back in the 00s on my modern Mac, and this seems to be the right item, but I think this ought to be brought to your attention. I'd like to know what your experience will be with their team to resolve the report.

Also note, this might make a good addition to the project's Security tab, although I'm not sure what GitHub's features are that tie in with it.

**Comment by agologan** [comment]
Yes, seemed like a false positive.
Ran the check again and it now shows up as clean.
Please note we also released a new version `v2.1` which may interest you.
