### ISSUE TITLE
version numbers don't match

### ISSUE THREAD

**Issue by core-code** [liquidx/webviewscreensaver#63]
i've downloaded version 2.1 from GitHub but after download it claims to be version 2.0

<img width="256" alt="Screenshot 2020-10-29 at 11 55 34" src="https://user-images.githubusercontent.com/1261954/97559476-c5af5100-19dd-11eb-8420-de1eac7758d1.png">

the CFBundleShortVersionString in the Info.plist doesn't line-up with the release version

**Comment by agologan** [comment]
Forgot to update it, thanks for noticing it.
You can grab the latest build if it bugs you:
https://github.com/liquidx/webviewscreensaver/actions/runs/366434215

**Comment by core-code** [comment]
awesome thanks
