### ISSUE TITLE
allow autoplay for embedded videos

### ISSUE THREAD

**Issue by ntessore** [liquidx/webviewscreensaver#67]
It would be nice to be able to allow autoplay e.g. for the HD earth live stream from the ISS: https://www.ustream.tv/embed/17074538?autoplay=true&controls=false&volume=0

**Comment by agologan** [comment]
I find it interesting that different people come back asking for support for the ISS feed (#52 #26 #11)
I'm happy to see ustream fixed autoplay that was broken when I tested #52 but unfortunately that fix works only in Chrome.
This screensaver uses WKWebView which is the same tech in Safari and testing there shows that autoplay isn't fully fixed.

However I can still recommend using a Youtube mirror like in #52 which there have been plenty of lately.
