### ISSUE TITLE
Zoom and Autoplay settings?

### ISSUE THREAD

**Issue by ifixr** [liquidx/webviewscreensaver#73]
A website in Safari has setting such as Zoom or Autoplay. I'm really in need for the Autoplay settings as I want this saver to also play videos on websites. It would be great if the saver honoured settings from Safari, or has settings for all websites it plays.

**Comment by trusktr** [comment]
I'm wondering about this too. Safari/Webkit (and pretty much all browsers) require user interaction such as click or touch in order to start playing audio.

Can we bypass this in webviewscreensaver?

**Comment by agologan** [comment]
User interaction yeah, that wouldn't work but not all websites require it, see https://github.com/liquidx/webviewscreensaver/issues/52 for some ideas.

I don't know about "honouring setting from Safari" part but I think you're referring saving website settings for which there is a fork.

**Comment by agologan** [comment]
Might want to try `v2.3` to preview and interact with the website during configuration. 
Cookies and local storage is shared. Won't solve every case.

Although advanced scripting is possible we aim to keep the project simple.
It should be easy enough to fork and add custom user scripts via `evaluateJavaScript` or `WKUserScript`.
