### ISSUE TITLE
issues with using a local folder / index.html as screensaver

### ISSUE THREAD

**Issue by leekslk** [liquidx/webviewscreensaver#80]
Currently, it only works after I first trigger it in preview but it gives a blank screen if the computer enters screensaver mode on its own. It seems to work for a second time, then failed on the third, etc. I'm still monitoring the frequency of successful activations.
The screensaver is from https://github.com/rafaelmaeuer/Dropclock
I saved it locally as a local file (index.html) stored on /Users/"username"/Dropclock-main.

I have a separate issue: after returning from screensaver and logging in, keyboard shortcuts involving the command key or function (fn) key does not work. A restart is currently the only way to clear the issue. I can reproduce this if I were to start the screensaver through Preview-mode (after the restart).

Happy to provide logs. I'm not sure where to look for possible conflicts as I am uncertain which are the activities related to screensaver as well as keyboard shortcuts.

Notes: following coofercat's discovery, I did force quit/kill a process linked to "legacyScreenSaver"
brew installation; M1 Max; Sonoma 14.2.1; Raycast installed; more details if necessary

**Comment by agologan** [comment]
`git clone --depth 1 https://github.com/rafaelmaeuer/Dropclock.git`
Put in the path, tested several times from preview, launched from Alfred and launched automatically on timer and all work fine.

If all works fine, `legacyScreenSaver` should disappear after a few seconds from Activity Monitor when closing Settings or returning from the screensaver.
`ps aux | grep legacyScreenSaver` would just show itself
If you don't see the process there and are  having keyboard issues it's 100% not it interfering.

Running Sonoma 14.2 on Intel (will update when I get some time) and WebViewScreenSaver **2.4**

**Comment by agologan** [comment]
Maybe there is a multi-screen issue.
How many monitors do you have connected? 
Please specify how many external monitors and if you're also using the built-in screen (if MacBook or clamshell mode)

**Comment by leekslk** [comment]
I have two external monitors, macbook pro screen is also on. Seems to work every other time for now.

**Comment by agologan** [comment]
Retested again today on MBP Pro with M3 and 1 external monitor and there's no issue.
Closing for now, but will keep an eye out if the issue resurfaces.
