### ISSUE TITLE
Doesn't load URL

### ISSUE THREAD

**Issue by relaxnow** [liquidx/webviewscreensaver#82]
I wanted to load it with https://relaxnow.github.io/cognitive-bias-codex-screensaver/index.html but that doesn't work. It just shows a black screen.
It does appear to work on https://relaxnow.github.io/vcsd/index.html or https://google.com just not on the above URL?
It does load in the preview.

**Comment by relaxnow** [comment]
I found that it works when I trim the nested "data" element down to 1 element. Which is annoying, the reason I'm inlining this 200Kb of data is that I wanted to store this locally so it works even without a network.

**Comment by relaxnow** [comment]
Ah, it also works when I remove newlines from the data element, that works for me as a workaround. Strange bug though, I'll leave the old version up in case you want to look at it.

**Comment by agologan** [comment]
Don't see any issue with it.
Remember this is using WKWebView so it needs to work in Safari.

**Comment by relaxnow** [comment]
Odd. It works in Safari, it works in the preview window, but when I start the screensaver I just get a black screen.
Anyway, I have a workaround, thanks for taking a look though @agologan

**Comment by agologan** [comment]
¯\_(ツ)_/¯ Do you mind leaving your OS version an CPU architecture here for posterity in case we run into similar issues?
I'm currently on Sonoma 14.1 on arm64

**Comment by relaxnow** [comment]
Oops, forgot about this, sure, I have Sonoma 14.5 on Intel.
